---
all:
  hosts:
    webserver1:
      ansible_host: 18.198.24.43
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/yurii/Downloads/main-keypait.pem

    webserver2:
      ansible_host: 35.159.117.204
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/yurii/Downloads/main-keypait.pem
# become: true