apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  labels:
    app: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
  minReadySeconds: 30 # seconds
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
        
          volumeMounts:
            - name: vol
              mountPath: /usr/share/elasticsearch/data
          
          env:
            - name: "discovery.type"
              value: "single-node"
            - name: "xpack.security.enabled"
              value: "false"
          ports:
            - name: es
              containerPort: 9200
  volumeClaimTemplates:
    - metadata:
        name: vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: es-svc
spec:
  type: ClusterIP
  selector:
    app: es
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.12.2
        ports:
        - containerPort: 5601
        env:
          - name: "ELASTICSEARCH_HOSTS"
            value: "http://es-svc:9200"

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
spec:
  type: ClusterIP
  selector: 
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush           1
        Log_Level       info
        Parsers_File    /fluent-bit/etc/parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            cri
        DB                /var/log/flb_kubernetes.db
        Mem_Buf_Limit     100MB
        Skip_Long_Lines   On

    [OUTPUT]
        Name            es
        Match           kube.*
        Host            es-svc
        Port            9200
        Logstash_Format  On
        suppress_type_name On
        Logstash_Prefix  kubernetes
        Retry_Limit      False
        Buffer_size False
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit

  template:
    metadata:
      labels:
        app: fluent-bit

    spec:
      tolerations:
        - operator: Exists

      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:4.1

          securityContext:
            runAsUser: 0

          volumeMounts:
            - name: varlog
              mountPath: /var/log

            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true

            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
              readOnly: true

            - name: parsers
              mountPath: /fluent-bit/etc/parsers.conf
              subPath: parsers.conf
              readOnly: true

      volumes:
        - name: varlog
          hostPath:
            path: /var/log

        - name: containers
          hostPath:
            path: /var/lib/docker/containers

        - name: config
          configMap:
            name: fluent-bit-config
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf

        - name: parsers
          configMap:
            name: fluent-bit-config
            items:
              - key: parsers.conf
                path: parsers.conf