apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_PASSWORD: "12345678"
  POSTGRES_DB: "petclinicdb"
  # POSTGRES_DB: "jdbc:postgresql://postgres-svc:5432/petclinic"
  POSTGRES_USERNAME: "postgres"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USERNAME
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: ClusterIP
  selector: 
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
